// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5eYIHy4w1LXzokULKIOwYzDg3qrVGepk',
    appId: '1:926725447107:web:2c7a86f0a4058c7ff0b176',
    messagingSenderId: '926725447107',
    projectId: 'sou-okaz',
    authDomain: 'sou-okaz.firebaseapp.com',
    storageBucket: 'sou-okaz.firebasestorage.app',
    measurementId: 'G-EE2PF23ZP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqlhqzdFB9cXyCUMyl7Ixioes2GO1541M',
    appId: '1:926725447107:android:cb6b765146221dd9f0b176',
    messagingSenderId: '926725447107',
    projectId: 'sou-okaz',
    storageBucket: 'sou-okaz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeBuj4bgFE0Mf4F58m568g_sQfSwiE9as',
    appId: '1:926725447107:ios:9c5c1d21a6de5a00f0b176',
    messagingSenderId: '926725447107',
    projectId: 'sou-okaz',
    storageBucket: 'sou-okaz.firebasestorage.app',
    androidClientId: '926725447107-d9ecjp4v4v65e7g7d9ve4vlrsg48g6lg.apps.googleusercontent.com',
    iosClientId: '926725447107-dghia61l23qmi0idk6cpo0mp8uks87m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashbaordSouOkaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeBuj4bgFE0Mf4F58m568g_sQfSwiE9as',
    appId: '1:926725447107:ios:9c5c1d21a6de5a00f0b176',
    messagingSenderId: '926725447107',
    projectId: 'sou-okaz',
    storageBucket: 'sou-okaz.firebasestorage.app',
    androidClientId: '926725447107-d9ecjp4v4v65e7g7d9ve4vlrsg48g6lg.apps.googleusercontent.com',
    iosClientId: '926725447107-dghia61l23qmi0idk6cpo0mp8uks87m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashbaordSouOkaz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5eYIHy4w1LXzokULKIOwYzDg3qrVGepk',
    appId: '1:926725447107:web:af0cf69b1aba29ccf0b176',
    messagingSenderId: '926725447107',
    projectId: 'sou-okaz',
    authDomain: 'sou-okaz.firebaseapp.com',
    storageBucket: 'sou-okaz.firebasestorage.app',
    measurementId: 'G-B1YET2YPWP',
  );
}
